version: '3.9'

services:
  pyzilla_server:
    build:
      args: 
        user: root
        uid: 0
      context: ./
      dockerfile: Dockerfile
    container_name: pyzilla_server
    working_dir: /var/www/
    ports:
      - 9600:80
    networks:
      - web_vowe
    command: sh ./pyzilla_server/start.sh

  
  # db

  # nginx


networks:
  web_py:
    driver: bridge